apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xcopy-pvc
  namespace: ${.POD_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
<<<<<<< HEAD
=======
  dataSource:
    apiGroup: forklift.konveyor.io
    kind: VSphereXcopyVolumePopulator
    name: test-xcopy
  dataSourceRef:
    apiGroup: forklift.konveyor.io
    kind: VSphereXcopyVolumePopulator
    name: test-xcopy
>>>>>>> 9c61b996 (certificate tool phase 1)
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${.STORAGE_CLASS_NAME}
  volumeMode: Block

