image: fedora-vm:latest
<<<<<<< HEAD
storageVendorProduct: "primera3par"
=======
storageVendorProduct: "ontap"
>>>>>>> 248c3298 (fix yaml parsing)
tests:
  - name: test-1
    success:
      maxTimeSeconds: 300
<<<<<<< HEAD
<<<<<<< HEAD
    vms:
      - namePrefix: testvm1
        size: 10Gi
=======
      vms:
        - namePrefix: testvm1
          size: 10Gi
>>>>>>> 248c3298 (fix yaml parsing)
=======
    vms:
      - namePrefix: testvm1
        size: 10Gi
>>>>>>> 7d84a3c1 (added polling for pods to finish)
