image: fedora-vm:latest
storageVendorProduct: "ontap"
hostName: host-3078
tests:
  - name: testb-1
    success:
      maxTimeSeconds: 300
    vms:
      - namePrefix: testvm1
        size: 10Gi
#      - namePrefix: testvm2
#        size: 10Gi