apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xcopy-storage-class
<<<<<<< HEAD
<<<<<<< HEAD
provisioner: csi.trident.netapp.io
parameters:
  volumeMode: Block
  allowMultiplePods: 'true'
  csi.storage.k8s.io/controller-expand-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  accessProtocol: iscsi

  description: "iscsi RWX Block volume by Ontap CSI Driver"
=======
provisioner: csi.hpe.com
=======
provisioner: csi.trident.netapp.io
>>>>>>> 85c76a6f (changes by Orr)
parameters:
  volumeMode: Block
  allowMultiplePods: 'true'
  csi.storage.k8s.io/controller-expand-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/controller-publish-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: rhosqe-netapp-c250-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  accessProtocol: iscsi

<<<<<<< HEAD
  description: "iscsi RWX Block volume by HPE CSI Driver"
>>>>>>> 9c61b996 (certificate tool phase 1)
=======
  description: "iscsi RWX Block volume by Ontap CSI Driver"
>>>>>>> 85c76a6f (changes by Orr)
  hostSeesVLUN: 'true'

reclaimPolicy: Delete
allowVolumeExpansion: true
<<<<<<< HEAD
<<<<<<< HEAD
volumeBindingMode: Immediate
=======
volumeBindingMode: Immediate

>>>>>>> 9c61b996 (certificate tool phase 1)
=======
volumeBindingMode: Immediate
>>>>>>> 85c76a6f (changes by Orr)
